### ISSUE TITLE
Ref - Token not supported

### ISSUE THREAD

**Issue by noemk2** [hummingbot/gateway#268]
**Describe the bug**
When I run a script (arbt_ref.py) or a POST to /amm/price I can't get the price
also think that wNear or USDC.e is not displayed because when making a get request to chain/tokens there is an error

arbt_ref.py 
```python
from decimal import Decimal
from typing import Dict

import pandas as pd

from hummingbot.client.ui.interface_utils import format_df_for_printout
from hummingbot.connector.connector_base import ConnectorBase
from hummingbot.data_feed.amm_gateway_data_feed import AmmGatewayDataFeed
from hummingbot.strategy.script_strategy_base import ScriptStrategyBase
from hummingbot.core.data_type.common import OrderType, PriceType, TradeType


class AMMDataFeedExample(ScriptStrategyBase):
    amm_data_feed_ref = AmmGatewayDataFeed(
        connector_chain_network="ref_near_mainnet",
        trading_pairs={"wNEAR-USDC.e"},
        order_amount_in_base=Decimal("1"),
    )

    markets = {"binance_paper_trade": {"BTC-USDT"}}

    def __init__(self, connectors: Dict[str, ConnectorBase]):
        super().__init__(connectors)
        self.amm_data_feed_ref.start()

    def on_stop(self):
        self.amm_data_feed_ref.stop()

    def on_tick(self):
        rows = []

        rows.extend(dict(price)
                    for token, price in self.amm_data_feed_ref.price_dict.items())

        price_ref = rows[0]["sell_price"]

        self.notify_hb_app_with_timestamp(price_ref)
        pass
```

output:
```bash
Error: {'message': 'Price query failed: Token not supported: wNEAR', 'httpErrorCode': 500, 'errorCode': 1013, 'stack': 'Error: Price query failed: Token not supported: wNEAR\n    at /home/gateway/dist/src/connectors/ref/ref.controllers.js:49:23\n    at Generator.throw (<anonymous>)\n    at rejected (/home/gateway/dist/src/connectors/ref/ref.controllers.js:6:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
```

**Steps To Reproduce**

- Execute arbt_ref.py on Hummingbot or make a POST request to /amm/price using Postman.

**Screenshots**
on hummingbot:
![Screenshot from 2024-01-21 14-08-23](https://github.com/hummingbot/gateway/assets/37389982/f6a1399d-b2e0-4a19-b8b1-7af60c1f3d41)
on postman POST request /amm/price:
![Screenshot from 2024-01-21 14-19-33](https://github.com/hummingbot/gateway/assets/37389982/53c56404-413b-4c92-9629-8c88f1794889)
on postman GET request  /chain/tokens:
![Screenshot from 2024-01-21 14-37-11](https://github.com/hummingbot/gateway/assets/37389982/1cf9c24b-0067-47a5-99d0-2d6ffbb4edda)

**Release version**
//  1.23.0

**Attachments**
// It is important that you attach the required files for us to be able to investigate the issue. 
// Please attach the chain.yml file from your gateway "conf" folder, e.g ethereum.yml

near.yml
```yml
networks:
  mainnet:
    chainID: 0
    nodeURL: https://rpc.mainnet.near.org
    tokenListType: FILE
    nativeCurrencySymbol: NEAR
    tokenListSource: /home/gateway/conf/lists/near_tokens.json
    gasPriceRefreshInterval: 60
  testnet:
    chainID: 0
    nodeURL: https://rpc.testnet.near.org
    tokenListType: FILE
    tokenListSource: /home/gateway/conf/lists/near_testnet_tokens.json
    nativeCurrencySymbol: NEAR
    gasPriceRefreshInterval: 60

gasLimitTransaction: 3000000000000
manualGasPrice: 0
```
