### ISSUE TITLE
Docker start fails when trying to copy template config

### ISSUE THREAD

**Issue by mattcasey** [hummingbot/gateway#460]
### Describe the bug

I am trying to run the latest gateway, but it is failing when it's time to set up the conf folder for the first time, because the templates path is the same as the config folder path: https://github.com/hummingbot/gateway/blob/f9e73298513595b3ed7e66bbfa5ed24c0ca6fd99/src/services/config-manager-v2.ts#L37.

```
gateway exited with code 1
gateway     | 
gateway     | > gateway@2.6.0 start /home/gateway
gateway     | > START_SERVER=true node dist/index.js
gateway     | 
gateway     | node:fs:3035
gateway     |   binding.copyFile(
gateway     |           ^
gateway     | 
gateway     | Error: ENOENT: no such file or directory, copyfile '/home/gateway/conf/root.yml' -> '/home/gateway/conf/root.yml'
gateway     |     at Object.copyFileSync (node:fs:3035:11)
gateway     |     at ConfigManagerV2.getInstance (/home/gateway/dist/services/config-manager-v2.js:188:30)
gateway     |     at getLogPath (/home/gateway/dist/services/logger.js:65:60)
gateway     |     at Object.<anonymous> (/home/gateway/dist/services/logger.js:70:18)
gateway     |     at Module._compile (node:internal/modules/cjs/loader:1529:14)
gateway     |     at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
gateway     |     at Module.load (node:internal/modules/cjs/loader:1275:32)
gateway     |     at Module._load (node:internal/modules/cjs/loader:1096:12)
gateway     |     at Module.require (node:internal/modules/cjs/loader:1298:19)
gateway     |     at require (node:internal/modules/helpers:182:18) {
gateway     |   errno: -2,
gateway     |   code: 'ENOENT',
gateway     |   syscall: 'copyfile',
gateway     |   path: '/home/gateway/conf/root.yml',
gateway     |   dest: '/home/gateway/conf/root.yml'
```

### Steps to reproduce
docker-compose.yml:
```
services:
  hummingbot:
    container_name: hummingbot
    image: hummingbot/hummingbot:latest
    build: # Uncomment this and comment image if you want to build it locally
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
  #    environment:
  #      - CONFIG_PASSWORD=a
  #      - CONFIG_FILE_NAME=v2_with_controllers.py
  #      - SCRIPT_CONFIG=conf_v2_with_controllers.yml

  gateway:
    restart: always
    container_name: gateway
    image: hummingbot/gateway:latest
    ports:
      - "15888:15888"
      - "8080:8080"
    volumes:
      - "./gateway_files/conf:/home/gateway/conf"
      - "./gateway_files/logs:/home/gateway/logs"
      - "./gateway_files/db:/home/gateway/db"
      - "./certs:/home/gateway/certs"
    environment:
      - GATEWAY_PASSPHRASE="a"
```

### Release version

2.6

### Type of installation

Docker
